#!groovy? 

node {
  
	   stage('Descargar Fuentes') { 
		  checkout scm
	   }     
	  
	   stage('Compilando con Maven')
	   {
		def prueba = bat "chdir"
		println("esto es una prueba")
		println(prueba)
		
		println("compilando")
	   }

	   stage('Deployment en JBOSS') {
	   
	   println("desplegando")
						
	 	
	}
}
