#!groovy? 
def JENKINS_WORKSPACE = 'C://Users/usuario/batch';
//def NAME_PROJECT_JENKINS = 'comercial-app';
//def NAME_JOB_JENKINS = 'comercial-backend';
def APP_NAME = 'comercial';
def ARCHIVO_BATCH = 'compiler-maven.bat'; 

def cmd_exec(command) {
    return bat(returnStdout: true, script: "${command}").trim()
}

node {
  
	   stage('Descargar Fuentes') { 
		  checkout scm
	   }     
	  
	   stage('Compilando con Maven')
	   {
	     
		//bat "cd ${JENKINS_WORKSPACE}/${APP_NAME}"
		powershell "cd comercial"
		powershell "mvn clean package -DskipTests"
		//bat "call ${ARCHIVO_BATCH}"
		
		println("compilando")
	   }

	   stage('Deployment en JBOSS') {	
	   
	   println("desplegando")
						
	 	
	}
}
