#!groovy?  
def jboss_prod_host = 'localhost:9990';
def jboss_prod_admin_user = 'admin';
def jboss_prod_admin_password = 'admin';
def aplicacion_compiler = 'comercial.war';

node {
  
	   stage('Descargar Fuentes') { 
		  checkout scm
	   }     
	  
	   stage('Compilando con Maven')
	   {
	   
	   dir('comercial') {
			bat "mvn clean package -DskipTests"
		}
	      
		println("compilado")
	   }

	   stage('Deployment en JBOSS') {	
	    dir('target') { 
		 bat "java -jar jboss-cli-client.jar --connect --controller=${jboss_prod_host} --user=${jboss_prod_admin_user} --password=${jboss_prod_admin_password} --command='undeploy comercial.war'";
		//def jboss-undeploy = " java -jar jboss-cli-client.jar --connect --controller=${jboss_prod_host} --user=${jboss_prod_admin_user} --password=${jboss_prod_admin_password} --command='undeploy comercial.war'";
		//bat jboss-undeploy;
				
		bat "java -jar jboss-cli-client.jar --connect --controller=${jboss_prod_host} --user=${jboss_prod_admin_user} --password=${jboss_prod_admin_password} --command='deploy ../../standalone/deployments/comercial.war --force'";
		//def jboss-deploy = " java -jar jboss-cli-client.jar --connect --controller=${jboss_prod_host} --user=${jboss_prod_admin_user} --password=${jboss_prod_admin_password} --command='deploy ../../standalone/deployments/comercial.war --force'";
		//bat jboss-deploy;
		 
		  
	   } 
	     
	   println("deplegado")
		 
	}
}
